sudo: false
dist: trusty


language: java


jdk:
  - openjdk8

services:
  - xvfb

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start


script: ./mvnw -Ptravis-ci clean install site

after_success:
  - bash <(curl -s https://codecov.io/bash)
