language: java


jdk:
  - openjdk13

install: skip

script:
  - ./mvnw -U -Pheadless site
  - ./mvnw -U -Pheadless clean install
  - chmod +x etc/devscripts/*.sh
  - etc/devscripts/buildAppImage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
